sudo: false

# Only build develop, master, and version tags (which are considered branches
# by Travis). PRs still get built.
branches:
  only:
    - develop
    - master
    - /^\d+\.\d+(\.\d+)*$/

language: python
python: '3.6'
cache: pip

install: pip install tox codecov
script: tox

after_success: if [[ $TOXENV =~ py..-(full|pytest3) ]]; then codecov; fi

jobs:
  include:
    - env: TOXENV=py34-core,py34-pytest,py34-testtools,py34-full
      python: '3.4'
      sudo: required
      services: docker

    - env: TOXENV=py35-core,py35-pytest,py35-testtools,py35-full
      python: '3.5'
      sudo: required
      services: docker

    - env: TOXENV=py36-core,py36-pytest,py36-testtools,py36-full
      python: '3.6'
      sudo: required
      services: docker

    - env: TOXENV=py37-core,py37-pytest,py37-testtools,py37-full
      python: '3.7'
      dist: xenial
      sudo: required
      services: docker

    # FIXME 2018-12-06: Some of our tests are not compatible with pytest 4. Run
    # a special build job just for them until we find a good alternative.
    # https://github.com/praekeltfoundation/seaworthy/issues/84
    - env: TOXENV=py37-pytest3
      python: '3.7'
      dist: xenial
      sudo: required
      services: docker

    - env: TOXENV=docs
    - env: TOXENV=pep8

    - stage: release
      if: tag IS present
      deploy:
        provider: pypi
        user: praekelt.org
        password:
          secure: Ud1nTOTBeFgHeJXig5bC5Bd9irYyvHvCEU2Kwdnn7MS/ta2w3D0Fqi7LZsrCWkP20p6FFG19Qim3dMm5VUCllJk+3uUrR/85WO4Eam6OQg+ZriGX1d76BA8fHj9CEap9IjSHQbeg1QBO0eCbhTpxNWt8Zoa2CDUti3ZRzwXGObLaQhYfUheuXmH0ONSx5LMST7jY00YKzfqosMtaO90qoJQiAg2LWIqBBRMmh5fM2F50DeBFEe1Cx9bAyugDeZgi2rdwKQ7/l3ZYsRS6XUXOWcjKimZ9b7JHZHWLSt3ccNPfpU6SqwuSG6+WIBvHfGNcG+Oj11Rs3xNKyd0KTKyERxrq2Qnwl3OlNTvnyiZydV3JreAKVlSWYwliAOXn37da66as9ENajIcDPKVuFo/2wn16bHmxH81lfdBULQZg3qpmGbyM65/uDiyukuYBiccooGcr5zND5NBFF7DXVV7NuaLBoMz+ehLAnC3frU+5gSp3F4wE6vtKackqbIy/H76BN1SYmkwfMB3SoqWywwueaQjd+a8YbPVpz6AIzEfSzQTgI+eXR7tf9NBxv2ZcaGvRrbkujMBN57GtQh5NcMtipXiGtun5AvivP9XletJnKDJa6iVJkcbm1tYbTnBt+j3Jwx2eKTECdV1+tQbdZKARoBLIbl8kp0GrVnyAHWQR1Ys=
        distributions: sdist bdist_wheel
        on: {tags: true}

      install: skip
      script: skip
